![](prac_4.png)

In [7]:
'''4(a) Write a program to calculate element-wise difference between the neighbouring elements of a given array.'''
import numpy as np
# number of elements
n = int(input("Enter number of elements : "))
# Read input
arr = list(map(int, input("\nEnter the numbers : ").split()))
print(arr)
b = np.diff(arr)
print(b)

[8, 9, 4, 5, 7]
[ 1 -5  1  2]


In [5]:
''' 4(e) Write a program to create a 5*5 array with random values and find the minimum and maximum values using NumPy.'''
from numpy import random
x = random.rand(5, 5)
print(x)
print(x.max())
print(x.min())

[[0.33303561 0.54904491 0.60346491 0.77585092 0.12454252]
 [0.55756794 0.96284926 0.65233639 0.67446033 0.97487677]
 [0.5642031  0.48727716 0.38761512 0.12037264 0.68193147]
 [0.95752018 0.16989562 0.9228318  0.37819966 0.92948009]
 [0.67669565 0.67923452 0.59079741 0.28172688 0.06080974]]
0.9748767663667711
0.060809736827945216


In [3]:
''' 4(d) Write a program to solve three linear equations with variables x, y, and z using NumPy.
        4x+3y+2z  = 25
        -2x+2y+3z = -10
        3x-5y+2z  = -4'''
import numpy as np
A = np.array([[4,3,2],[-2,2,3],[3,-5,2]])
B = np.array([25,-10,-4])
#x = np.linalg.inv(A).dot(B)
#print(x)
x2 = np.linalg.solve(A,B)
print(x2) 

[ 5.  3. -2.]


In [12]:
'''Write a program using NumPy to multiply two user-defined matrices of size n*n where n > 2.'''
x =  np.arange(1, 10).reshape(3,3)
print(x)

b = x.transpose()
print (b)
print (np.linalg.det(x))
print (np.linalg.det(b))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
6.66133814775094e-16
0.0


In [9]:
'''4(c) Write a program to take a 3*3 array (matrix) from the user and calculate its transpose as well as determinant. 
Also, find whether the matrix is invertible; if yes, find the inverse of the matrix.'''
import numpy as np 
#Taking a 4*4 matrix
Rows = int(input("Enter the number of rows:"))
Columns = int(input("Enter the number of columns:"))
print("Enter the values")
# values input of entries
values = list(map(int,input().split()))
# matrix
matrix = np.array(values).reshape(Rows,Columns)
print(matrix)
#calculating question
print("Determinant:")
print(np.linalg.det(matrix))
print("Transpose:")
print(np.matrix.transpose(matrix))
print("Inverse:")
print(np.linalg.inv(matrix))

Enter the values
[[5 6 7]
 [4 5 6]
 [7 8 9]]
Determinant:
2.664535259100367e-15
Transpose:
[[5 4 7]
 [6 5 8]
 [7 6 9]]
Inverse:
[[-1.12589991e+15  7.50599938e+14  3.75299969e+14]
 [ 2.25179981e+15 -1.50119988e+15 -7.50599938e+14]
 [-1.12589991e+15  7.50599938e+14  3.75299969e+14]]
