![](prac_6.png)

##### 6.(a) Create a .txt file with at least ten lines and write a program to perform the following tasks.
1. Stream the data in the file.
2. Display text at the odd numbered lines in the file.
3. Randomly sample 30% lines and display.
4. Read the file using pandas for parsing.'''


In [13]:
print("-----Task-1-----")
file = open("new.txt", "w")
lines = ["Hey,\n", "my\n", "name is\n", "Devarshee Shah\n", "and i am\n","ICT A\n", "Sem-5\n", "in AIIE\n",
"Thanks for visiting\n", "Bye!!\n"]
file.writelines(lines)
print(file)
file.close()

-----Task-1-----
<_io.TextIOWrapper name='new.txt' mode='w' encoding='UTF-8'>


In [ ]:
print("-----Task 2-----")
fn = open('new.txt', 'w+')
cont = fn.readlines()
type(cont)
for i in range(0, len(cont)):
    if (i % 2 != 0):
    fn1.write(cont[i])
    else:
    pass
fn1.close()
fn1 = open('New.txt', 'r')
cont1 = fn1.read()
print(cont1)
fn.close()
fn1.close()

In [14]:
print("-----Task 3-----")
import random
file = open('new.txt','r')
lines = file.readlines()
x: int = (len(lines))
y = 3
print(random.sample(lines, y))
file.close()

-----Task 3-----
['Bye!!\n', 'in AIIE\n', 'Thanks for visiting\n']


In [15]:
print("-----Task 4-----")
import pandas as pd
data= pd.read_fwf('new.txt') #Read a table of fixed-width formatted lines into DataFrame.
print(data)

-----Task 4-----
                  Hey,
0                   my
1              name is
2       Devarshee Shah
3             and i am
4                ICT A
5                Sem-5
6              in AIIE
7  Thanks for visiting
8                Bye!!


#### 6.(b) Create or download a .csv file from the publically available datasets and write a program to perform the following tasks.
1. Read the file using pandas for parsing.
2. Display any two columns from the file.
3. Display any two records (rows) from the file.

In [6]:
import pandas as pd
df = pd.read_csv('diabetes.csv')
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [5]:
df[['Glucose', 'BMI']]


Glucose   BMI
0        148  33.6
1         85  26.6
2        183  23.3
3         89  28.1
4        137  43.1
..       ...   ...
763      101  32.9
764      122  36.8
765      121  26.2
766      126  30.1
767       93  30.4

[768 rows x 2 columns]

In [11]:
# Print selected rows based on the condition
selected_rows = pd.read_csv('diabetes.csv',nrows=2)
print(selected_rows)

   Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  


##### 6.(c) Create or download a .xls file from the publically available datasets with at least three worksheets and write a program to perform the following tasks using pandas for parsing.
1. Read sheet2 from .xls and display it.
2. Read specific columns from the file and display them.
3. Add a column in sheet2 of the file and fill it with NaN values.

In [10]:
import pandas as pd
import numpy as np
print("\n-----Task 1-----\n")
df = pd.read_excel("C:/Users/DEVARSHI SHAH/Desktop/time.xlsx", sheet_name='sheet2')
print(df)



-----Task 1-----

                 TIMINGS    MON (ICT_A)                ELE    MON (ICT_B)  \
0       9:00 to 10:00 am      FLAT(HRC)         L1-EM (PM)  B2-OOP-J (RP)   
1      10:00 to 11:00 am       PYD (KC)         L1-EM (PM)  B2-OOP-J (RP)   
2   11:00 am to 12:00 pm        OR (JT)            SS (SJ)       ADA (VK)   
3       12:00 to 1:00 pm            NaN        EM-II (AKS)       ANP (MS)   
4                    NaN            NaN                NaN            NaN   
5                TIMINGS    TUE (ICT_A)                ELE    TUE (ICT_B)   
6       9:00 to 10:00 am    A3-PYD (KC)         L1-SS (PM)            NaN   
7      10:00 to 11:00 am    A3-PYD (KC)         L1-SS (PM)       PYD (IY)   
8   11:00 am to 12:00 pm        OR (JT)        Python (RJ)    B2-ADA (VK)   
9       12:00 to 1:00 pm     OOP-J (VC)        EM-II (AKS)    B2-ADA (VK)   
10                   NaN            NaN                NaN            NaN   
11               TIMINGS    WED (ICT_A)                EL

In [12]:
print("\n-----Task 2-----\n")
df = pd.read_excel('C:/Users/DEVARSHI SHAH/Desktop/time.xlsx', index_col=None, na_values=['NA'], usecols = "A:B")
print(df)


-----Task 2-----

                 TIMINGS    MON (ICT_A)
0       9:00 to 10:00 am      FLAT(HRC)
1      10:00 to 11:00 am       PYD (KC)
2   11:00 am to 12:00 pm        OR (JT)
3       12:00 to 1:00 pm            NaN
4                    NaN            NaN
5                TIMINGS    TUE (ICT_A)
6       9:00 to 10:00 am    A3-PYD (KC)
7      10:00 to 11:00 am    A3-PYD (KC)
8   11:00 am to 12:00 pm        OR (JT)
9       12:00 to 1:00 pm     OOP-J (VC)
10                   NaN            NaN
11               TIMINGS    WED (ICT_A)
12      9:00 to 10:00 am     A3-DE (UG)
13     10:00 to 11:00 am     A3-DE (UG)
14  11:00 am to 12:00 pm        OR (JT)
15      12:00 to 1:00 pm       PYD (KC)
16                   NaN            NaN
17               TIMINGS   THUR (ICT_A)
18      9:00 to 10:00 am  A3-OOP-J (VC)
19     10:00 to 11:00 am  A3-OOP-J (VC)
20  11:00 am to 12:00 pm            NaN
21      12:00 to 1:00 pm            NaN
22                   NaN            NaN
23               TIMI

In [11]:
print("\n-----Task 3-----\n")
df = pd.read_excel('C:/Users/DEVARSHI SHAH/Desktop/time.xlsx', sheet_name='sheet2')
df.insert(2, "column1", np.nan)
print(df.head)


-----Task 3-----

<bound method NDFrame.head of                  TIMINGS    MON (ICT_A)  column1                ELE  \
0       9:00 to 10:00 am      FLAT(HRC)      NaN         L1-EM (PM)   
1      10:00 to 11:00 am       PYD (KC)      NaN         L1-EM (PM)   
2   11:00 am to 12:00 pm        OR (JT)      NaN            SS (SJ)   
3       12:00 to 1:00 pm            NaN      NaN        EM-II (AKS)   
4                    NaN            NaN      NaN                NaN   
5                TIMINGS    TUE (ICT_A)      NaN                ELE   
6       9:00 to 10:00 am    A3-PYD (KC)      NaN         L1-SS (PM)   
7      10:00 to 11:00 am    A3-PYD (KC)      NaN         L1-SS (PM)   
8   11:00 am to 12:00 pm        OR (JT)      NaN        Python (RJ)   
9       12:00 to 1:00 pm     OOP-J (VC)      NaN        EM-II (AKS)   
10                   NaN            NaN      NaN                NaN   
11               TIMINGS    WED (ICT_A)      NaN                ELE   
12      9:00 to 10:00 am    

##### 6(d) Write a program to perform the following tasks using an image from online source using skimage.
1. Display the original image.
2. Display the image in gray scale.
3. Find the shape and type of the image.
4. Display a cropped version of the image.
5. Display a resized version of the image.

In [19]:
import skimage.io
import skimage.color
from matplotlib import pyplot as plt
from skimage.transform import resize
from skimage.util import crop
print("-----Task 1-----")
image = skimage.io.imread("photo2.jpeg")
print(image)

-----Task 1-----
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
